// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	AddWalletBalance(ctx context.Context, arg AddWalletBalanceParams) (Wallet, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	DeleteCategory(ctx context.Context, id int64) error
	DeleteTransaction(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteWallet(ctx context.Context, id int64) error
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetTransaction(ctx context.Context, id int64) (Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetWallet(ctx context.Context, id int64) (Wallet, error)
	GetWalletForUpdate(ctx context.Context, id int64) (Wallet, error)
	ListCategories(ctx context.Context, userID int64) ([]Category, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	ListWallets(ctx context.Context, userID int64) ([]Wallet, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error)
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallet, error)
}

var _ Querier = (*Queries)(nil)
